version: '3'
services:
  api:
    image: node:16.16.0
    command: sh -c 'npm install && npm run server --env=dev'
    container_name: api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-dataset:/data/db

volumes:
  mongo-dataset:
